# Generated by Django 4.2 on 2023-04-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_app', '0003_alter_propertyimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='live_app.property'),
        ),
    ]
