# Generated by Django 4.2 on 2023-05-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_app', '0005_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='property',
        ),
    ]
